[package]
name = "uniprops"
version = "0.2.1"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Small library for converting unicode decimal into numbers"
authors = ["vloldik (@vloldik)"]
keywords = ["text", "unicode", "decimal"]
categories = ["text-processing"]
readme = { workspace = true }
repository = "https://github.com/vloldik/uniprops"
documentation = "https://docs.rs/uniprops"

[dependencies]
uniprops_gen = { path = "../uniprops_gen", version = "0.2.1" }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "decimal_extended_benchmark"
harness = false
