[package]
name = "uniprops-gen"
version = "0.3.3"
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
description = "A code generation library for creating optimized Unicode property lookups"
repository = "https://github.com/vloldik/uniprops"
categories = ["development-tools::build-utils", "internationalization"]
keywords = ["unicode", "codegen", "build-rs"]
readme = { workspace = true }

[dependencies]
csv = "1.3"
quote = "1.0.40"
serde = { version = "1.0.219", features = ["derive"] }
proc-macro2 = "1.0"
