[package]
name = "uniprops-gen"
version = "0.3.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Gen package for uniprops library"

[dependencies]
csv = "1.3"
quote = "1.0.40"
serde = { version = "1.0.219", features = ["derive"] }
