[package]
name = "uniprops-gen"
version = "0.2.1"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Gen package for uniprops library"

[dependencies]
csv = "1.3"
quote = "1.0.40"
proc-macro2 = "1.0"
serde = { version = "1.0.219", features = ["derive"] }

[lib]
proc-macro = true
